FROM python:3.12-alpine

RUN apk add --no-cache bash curl docker-cli

WORKDIR /app

COPY docker/router/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY docker/router /app/router

CMD ["python", "/app/router/router.py"]
